RESULTS.FILE <- '/home/ob219/share/as_basis/GWAS/RESULTS/02_08_19_0619_primary_results.RDS'
res.DT <- readRDS(RESULTS.FILE)
keep.cat <- c('bowes_jia_2019',
  'bb_disease',
  'myogen',
  'estrada_NMO',
  'lyons_egpa',
  'bowes_psa',
  'kiryluk_iga_neph',
  'brown_as',
  'cousminer_lada',
  'li_as',
  'psa_aterido',
  'hasnoot_uveitis_jia',
  'ahola-olli_cytokine')
res.DT <- res.DT[category %in% keep.cat,]
res.DT[category=='ahola-olli_cytokine',trait:=gsub("CK:","",trait)]
res.DT[,c('first.author','shiny.category'):=tstrsplit(category,'_')]
res.DT[first.author=='bb',first.author:='Neale']
res.DT[first.author=='psa',first.author:='Aterido']
res.DT[,reference:='unpublished']
res.DT[,trait.label:=trait]

res.DT[trait.label=='jia_ERA_19',trait.label:='enthesitis_related_jia']
res.DT[trait.label=='jia_EO_19',trait.label:='extended_oligo_jia']
res.DT[trait.label=='jia_PO_19',trait.label:='persistent_oligo_jia']
res.DT[trait.label=='jia_PsA_19',trait.label:='psoriatic_jia']
res.DT[trait.label=='jia_RFneg_19',trait.label:='polyoligo_rf-_jia']
res.DT[trait.label=='jia_RFpos_19',trait.label:='polyoligo_rf+_jia']
res.DT[trait.label=='jia_undiff_19',trait.label:='undifferentiated_jia']
res.DT[trait.label=='jia_sys_19',trait.label:='systemic_jia']
res.DT[trait.label=='jia_case_19',trait.label:='combined_jia']
res.DT[grep('jia$',trait.label),reference:='unpublished']
res.DT[trait.label=='CD_prognosis',trait.label:='crohns_disease_prognosis']
res.DT[trait.label=='crohns_disease_prognosis',reference:='28067912']
res.DT[trait.label=='ADHD',trait.label:='attention_deficit_hyperactivity_disorder']
res.DT[trait.label=='attention_deficit_hyperactivity_disorder',reference:='29325848']
res.DT[reference=='29325848',first.author:='martin']
res.DT[trait.label=='BIP',trait.label:='bipolar_disorder']
res.DT[trait.label=='bipolar_disorder',reference:='29906448']
res.DT[trait.label=='SCZ',trait.label:='schizophrenia']
res.DT[trait.label=='schizophrenia',reference:='29906448']
res.DT[reference=='29906448',first.author:='psyc_consortium']
res.DT[trait.label=='myositis_myogen',trait.label:='combined_myositis']
res.DT[trait.label=='jdm_myogen',trait.label:='juvenile_dermatomyositis']
res.DT[trait.label=='dm_myogen',trait.label:='dermatomyositis']
res.DT[trait.label=='pm_myogen',trait.label:='polymyositis']
res.DT[trait.label=='NMO_combined',trait.label:='combined_neuromyelitis_optica']
res.DT[trait.label=='NMO_IgGNeg',trait.label:='igg-_neuromyelitis_optica']
res.DT[trait.label=='NMO_IgGPos',trait.label:='igg+_neuromyelitis_optica']
res.DT[grep('neuromyelitis_optica$',trait.label),reference:='29769526']
res.DT[trait.label=='anca_Neg',trait.label:='anca-_egpa']
res.DT[trait.label=='egpa',trait.label:='combined_egpa']
res.DT[trait.label=='mpo',trait.label:='mpo+_egpa']
res.DT[grep('egpa$',trait.label),reference:='https://doi.org/10.1101/491837']
res.DT[trait.label=='mpo_Pos',trait.label:='mpo+_aav']
res.DT[trait.label=='mpo+_aav',reference:='22808956']
## get rid of abdef
res.DT <- res.DT[trait.label!='ABDEF',]
res.DT[trait.label=='alloa',trait.label:='combined_osteoarthritis']
res.DT[trait.label=='hipkneeoa',trait.label:='hip_knee_osteoarthritis']
res.DT[trait.label=='hipoa',trait.label:='hip_osteoarthritis']
res.DT[trait.label=='kneeoa',trait.label:='knee_osteoarthritis']
res.DT[grep('osteoarthritis$',trait.label),reference:='29559693']
res.DT[trait.label=='bowes_psa',trait.label:='psoriatic_arthritis_unpublished']
res.DT[trait.label=='IgA_nephropathy',trait.label:='iga_nephropathy']
res.DT[trait.label=='iga_nephropathy',reference:='25305756']
res.DT[trait.label=='cousminer_lada',trait.label:='latent_autoimmune_diabetes_in_adults']
res.DT[trait.label=='latent_autoimmune_diabetes_in_adults',reference:='30254083']
res.DT[trait.label=='li_as',trait.label:='ankylosing_spondylitis_li']
res.DT[trait.label=='ankylosing_spondylitis_li',reference:='30946743']
res.DT[trait.label=='ank_spond',trait.label:='ankylosing_spondylitis_tasc']
res.DT[trait.label=='ankylosing_spondylitis_tasc',reference:='20062062']
res.DT[trait.label=='mahajan_t2d',trait.label:='type_2_diabetes']
res.DT[trait.label=='type_2_diabetes',reference:='30297969']
res.DT[trait.label=='na_psa',trait.label:='psoriatic_arthritis_north_america']
res.DT[trait.label=='psoriatic_arthritis_north_america',reference:='30552173']
res.DT[trait.label=='span_psa',trait.label:='psoriatic_arthritis_spanish']
res.DT[trait.label=='psoriatic_arthritis_spanish',reference:='30552173']
res.DT[trait.label=='hasnoot_uveitis_jia',trait.label:='uveitis_jia']
res.DT[trait.label=='uveitis_jia',reference:='29513936']
res.DT[first.author=='ahola-olli',reference:='27989323']
res.DT[first.author=='kuiper',reference:='24957906']
res.DT[first.author=='taylor',reference:='29795407']
res.DT[first.author=='ferreira',reference:='29083406']
res.DT[first.author=='tian',reference:='28928442']
res.DT[first.author=='astle',reference:='27863252']
res.DT[is.na(shiny.category),shiny.category:='myositis']
res.DT[shiny.category=='disease',shiny.category:='UKBB Self-reported Disease']
res.DT[shiny.category=='iga',shiny.category:='IgA Nephropathy']
res.DT[shiny.category=='jia',shiny.category:='Juvenile Idiopathic Arthritis']
res.DT[shiny.category=='egpa',shiny.category:='Eosinophilic Granulomatosis with Polyangiitis']
res.DT[shiny.category=='psa',shiny.category:='Psoriatic Arthritis']
res.DT[shiny.category=='aterido',shiny.category:='Psoriatic Arthritis']
res.DT[shiny.category=='lada',shiny.category:='Latent Autoimmune Diabetes in Adults']
res.DT[shiny.category=='uveitis',shiny.category:='Uveitis in JIA']
res.DT[shiny.category=='cytokine',shiny.category:='Cytokine Levels']
res.DT[shiny.category=='NMO',shiny.category:='Neuromyelitis Optica']
res.DT[shiny.category=='myositis',shiny.category:='Myositis']
res.DT[shiny.category=='as',shiny.category:='Ankylosing Spondylitis']
res.DT[trait.label=='psoriatic_arthritis_spanish',first.author:='aterido']
res.DT[trait.label=='psoriatic_arthritis_north_america',first.author:='aterido']
res.DT[,shiny.label:=trait.label]
res.DT[shiny.category!='UKBB Self-reported Disease',shiny.label:=paste(first.author,trait.label,sep=':')]
saveRDS(res.DT,"~/tmp/02_08_19_0619_primary_results_shiny.RDS")
